import localFont from "next/font/local";
import "./globals.css";
import NabVar from "@/components/Nabvar/NabVar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Gorur Ghash",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Favicon linked from the public folder */}
        <link rel="icon" href="/public/Header-1.png" type="image/png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <NabVar></NabVar>
          {children}
        </div>
      </body>
    </html>
  );
}
