import { Poppins } from "next/font/google";
import "./globals.css";
import NabVar from "@/components/Nabvar/NabVar";

// Import Poppins font from Google Fonts
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Gorur Ghash",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Correct favicon path, without 'public' in the path */}
        <link rel="icon" href="/download (1).png" type="image/png" />
      </head>
      <body className={`${poppins.variable} antialiased`}>
        <div>
          <NabVar />
          {children}
        </div>
      </body>
    </html>
  );
}
