import Image from "next/image";
export const metadata = {
  title: "Gorur Ghash - Home",
  description: "Generated by create next app",
};
export default function Home() {
  return <div>home</div>;
}
